version: '3.8'

services:
  backend:
    image: node:16
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm start"
    env_file:
      - .env
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: Dockerfile.database
      args:
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
    ports:
      - '4000:4000'
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data: {}
