# version: 2.1
# jobs:
#   build_and_test:
#     docker:
#       - image: circleci/node:16
#         environment:
#           POSTGRES_DB: test_nomad
#           POSTGRES_USER: postgres
#           POSTGRES_PASSWORD: 1234
#           POSTGRES_HOST: localhost
#       - image: circleci/postgres:13
#         environment:
#           POSTGRES_DB: test_nomad
#           POSTGRES_USER: postgres
#           POSTGRES_PASSWORD: 1234
#     steps:
#       - checkout 
#       - run:
#           name: Install Dependencies
#           command: |
#             npm install
#             npm install coveralls --save-dev
#       - run:
#           name: Wait for PostgreSQL
#           command: |
#             for i in `seq 1 10`;
#             do
#               nc -z localhost 5432 && echo Success && exit 0
#               echo -n .
#               sleep 1
#             done
#             echo Failed waiting for PostgreSQL && exit 1
#       - run:
#           name: Fix Permissions
#           command: |
#             chmod +x node_modules/.bin/mocha
#             chmod +x ./node_modules/.bin/nyc
#             chmod +x ./node_modules/.bin/sequelize
#             chmod +x ./node_modules/.bin/sequelize-cli
#       - run:
#           name: Run Database Migrations
#           command: npx sequelize-cli db:migrate
#       - run:
#           name: Run Tests
#           command: npm test  
#       - run:
#           name: Build app
#           command: npm run build  
#       - run:
#           name: Generate Coverage Report
#           command: npm test -- --coverage
#       - run:
#           name: Upload Coverage to Coveralls
#           command: |
#             cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

# workflows:
#   version: 2
#   build:
#     jobs:
#       - build_and_test
version: 2.1
jobs:
  build_and_test:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Start Database Container Only
          command: docker-compose up -d database
      - run:
          name: Wait for Database
          command: sleep 15
      - run:
          name: Install Dependencies
          command: docker-compose run --rm backend npm install
      - run:
          name: Fix Permissions
          command: |
            docker-compose run --rm backend chmod +x node_modules/.bin/mocha
            docker-compose run --rm backend chmod +x ./node_modules/.bin/nyc
            docker-compose run --rm backend chmod +x ./node_modules/.bin/sequelize
            docker-compose run --rm backend chmod +x ./node_modules/.bin/sequelize-cli
      - run:
          name: Run Tests
          command: |
            docker-compose run --rm \
            -e NODE_ENV=test \
            backend npm test
      - run:
          name: Generate Coverage Report
          command: |
            docker-compose run --rm \
            -e NODE_ENV=test \
            backend npm test -- --coverage
      - run:
          name: Upload Coverage to Coveralls
          command: |
            docker-compose run --rm backend cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
      - run:
          name: Stop containers
          command: docker-compose down
          when: always

workflows:
  version: 2
  build:
    jobs:
      - build_and_test